# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: "3.8"

services:

  hdhs:
    container_name: "hdhs"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "10580:8443"
    volumes:
      - ./app:/home/hdhsuser/app
      - ./logs:/home/hdhsuser/logs
